#! /bin/sh

NAME=qemu

. $(dirname $0)/build

do_or_die "$SRC_DIR/configure" --prefix="$PREFIX" --enable-cap-ng --enable-attr --enable-vhost-net --enable-guest-base --enable-sdl --enable-vnc --enable-virtfs --enable-curl --enable-curses  --enable-fdt --enable-kvm --enable-system --enable-user  --enable-tcg-interpreter --enable-nptl --enable-guest-agent
make_and_install
