#! /bin/sh

# Expects $NAME to be set
# And sourced in build script.

. "$(dirname "$0")/helpers"
if [ -z "$NAME" ]; then
	warn "\$NAME is unset, fix build script"
	exit 1
fi

load_config

SRC_DIR=$GIT_DIR/$NAME
PREFIX=$PREFIX_DIR/$NAME
mkdir -p "$TMPDIR/build-$NAME"
BUILD_DIR="$(mktemp -d  "$TMPDIR/build-$NAME/XXXXX")"

cd "$BUILD_DIR" || die "Failed to cd to \"$BUILD_DIR\""
