#! /bin/sh

if [ -z "$GIT_DIR" ]; then
  GIT_DIR="$HOME/g"
fi

if [ -z "PREFIX_DIR" ]; then
  PREFIX_DIR="$HOME/x"
fi

#TMPDIR=/tmp
MAKE_OPTS="-j8"

CFLAGS="-march=native -O2 -flto"
CXXFLAGS="$CFLAGS"
LDFLAGS="$CFLAGS -Wl,--as-needed,--build-id -fuse-linker-plugin"
