#! /bin/sh

# "Linux Build"

if [ $# -lt 1 ]; then
	echo "usage: $(basename $0) <variant-name> [ <variant-base-name> | <config-file> ]"
fi

MAKE_OPTS="-j8 KCFLAGS="-fvar-tracking-assignments -g3 -gdwarf-4"
MAKE_ENV="ARCH=x86_64 CROSS_COMPILE=x86_64-linux-"

B=$HOME/build
V=$1
if ! [ -e "$B/$V/.config" ]; then
	need_config=true
else
	need_config=false
fi

if [ $# -eq 2 ]; then
	BV=$2
	if [ -e $B/$BV ]; then
		bv_is_variant_base=true
	else
		bv_is_variant_base=false
	fi
	if [ -e $BV ]; then
		bv_is_config_file=true
	else
		bv_is_config_file=false
	fi
fi

$MAKE_ENV make O=$B/$V $MAKE_OPTS
